CREATE DATABASE SHOPPE;
USE SHOPPE;


CREATE TABLE CATEGORY (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50)
);

CREATE TABLE PRODUCT (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    PRICE BIGINT,
    C_ID INT,
	FOREIGN KEY (C_ID) REFERENCES CATEGORY (ID)
);

CREATE TABLE VARIANT (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    SIZE INT,
    COLOR VARCHAR(30),
    P_ID INT,
    FOREIGN KEY (P_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE `USER` (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(50) UNIQUE,
    PASSWORD VARCHAR(50)
);

CREATE TABLE CART(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    U_ID INT UNIQUE,
    FOREIGN KEY (U_ID) REFERENCES `USER`(ID)
);

CREATE TABLE CART_DETAIL (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	QUANTITY INT,
    P_ID INT,
    C_ID INT,
    V_ID INT,
    FOREIGN KEY (P_ID) REFERENCES PRODUCT (ID),
    FOREIGN KEY (C_ID) REFERENCES CART (ID),
    FOREIGN KEY (V_ID) REFERENCES VARIANT (ID)
);

CREATE TABLE `ORDER` (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	ADDRESS_FROM VARCHAR(100),
    U_ID INT,
    FOREIGN KEY (U_ID) REFERENCES `USER`(ID)
);

CREATE TABLE ORDER_DETAIL (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	QUANTITY INT,
    P_ID INT,
    O_ID INT,
	V_ID INT,
    FOREIGN KEY (P_ID) REFERENCES PRODUCT (ID),
    FOREIGN KEY (O_ID) REFERENCES `ORDER` (ID),
    FOREIGN KEY (V_ID) REFERENCES VARIANT (ID)
);